# netlify.toml
[[plugins]]
  package = "netlify-plugin-minify-html"
  [plugins.inputs]
    # Run the plugin in these deploy contexts (optional)
    contexts = ["production", "deploy-preview", "branch-deploy"]

    # Pass options to html-minifier-terser here
    minifierOptions = { 
      collapseWhitespace = true,
      removeComments = true,
      removeRedundantAttributes = true,
      useShortDoctype = true,
      minifyCSS = true,
      minifyJS = true
    }
