[build]
# static site in the repo root; no build step
publish = "."

# HTML minify plugin (managed by Netlify, not package.json)
[[plugins]]
package = "netlify-plugin-minify-html"

  # Optional: uncomment to be explicit
  # [plugins.inputs.minifierOptions]
  # collapseWhitespace = true
  # removeComments = true
  # minifyCSS = true
  # minifyJS = true
